### ISSUE TITLE
mention --extra=+f in ~/.ctags

### ISSUE THREAD

**Issue by Konfekt** [ToruIwashita/nimble-anyjump.vim#9]
By adding `--extra=+f` to `~/.ctags` filenames become tags, too, so that
```vim
nnoremap <expr> <c-]> ':<c-u>tjump ' . expand('<cfile>:t') . '<CR>'
```
jumps to the file name under the cursor.

**Comment by Konfekt** [comment]
For a map that jumps to a tag if it exists, otherwise to a file name, use
```vim
nnoremap <expr> <c-]> !empty(taglist('\V\^' . escape(expand('<cword>'), '\') . '$')) ?
                  \   "<c-]>" : ":<c-u>tselect " . expand('<cfile>:t') . "<CR>"
```
and vice-versa, for a map that jumps to a file if it exists, otherwise to the tag created by `ctags --extra+f`, use
```vim
nnoremap <expr> gf empty(taglist('\V\^' . escape(expand('<cfile>'), '\') . '$')) ?
      \ "gf" : ":<c-u>tjump " . expand('<cfile>:t') . "<CR>"
```

**Comment by ToruIwashita** [comment]
@Konfekt 
To be honest I did not know the existence of `gf`. The same is true for `--extra=+f`. This plugin seems to be improved by using `--extra = + f` or` gf`, so I will try to improve it soon.

Thank you for this mention.

**Comment by ToruIwashita** [comment]
I implemented the corresponding function with this PR.
https://github.com/ToruIwashita/nimble-anyjump.vim/pull/10

Thank you for opening the issue!
